/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;

/**
 * @author Student
 */
public class guiShowTrack extends javax.swing.JFrame {

    /**
     * Creates new form guiShowTrack
     */
    public guiShowTrack() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jPanelR = new javax.swing.JPanel();
        jPaneL = new javax.swing.JPanel();
        jComboBoxDelay = new javax.swing.JComboBox();
        Delay = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Tracks = new javax.swing.JLabel();
        Inliers = new javax.swing.JLabel();
        Faults = new javax.swing.JLabel();
        FPS = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanelArrow = new javax.swing.JPanel();
        jTextFieldTracks = new javax.swing.JTextField();
        jTextFieldX = new javax.swing.JTextField();
        jTextFieldFaults = new javax.swing.JTextField();
        jTextFieldFPS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldZ = new javax.swing.JTextField();
        jTextFieldInliers = new javax.swing.JTextField();
        Speed = new javax.swing.JLabel();
        jTextFieldSpeed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelRLayout = new javax.swing.GroupLayout(jPanelR);
        jPanelR.setLayout(jPanelRLayout);
        jPanelRLayout.setHorizontalGroup(jPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 332, Short.MAX_VALUE));
        jPanelRLayout.setVerticalGroup(jPanelRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));

        javax.swing.GroupLayout jPaneLLayout = new javax.swing.GroupLayout(jPaneL);
        jPaneL.setLayout(jPaneLLayout);
        jPaneLLayout.setHorizontalGroup(jPaneLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 607, Short.MAX_VALUE));
        jPaneLLayout.setVerticalGroup(jPaneLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));

        jComboBoxDelay
                .setModel(new javax.swing.DefaultComboBoxModel(new String[]{"0 sec", "0.5 sec", "1 sec", "3 sec"}));
        jComboBoxDelay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDelayActionPerformed(evt);
            }
        });

        Delay.setText("Delay");

        Tracks.setText("Tracks");

        Inliers.setText("Inliers");

        Faults.setText("Faults");

        FPS.setText("FPS");

        jLabel6.setText("X");

        jTextFieldY.setEditable(false);
        jTextFieldY.setBackground(new Color(255, 255, 255));
        jTextFieldY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldYActionPerformed(evt);
            }
        });

        jLabel7.setText("Y");

        javax.swing.GroupLayout jPanelArrowLayout = new javax.swing.GroupLayout(jPanelArrow);
        jPanelArrow.setLayout(jPanelArrowLayout);
        jPanelArrowLayout.setHorizontalGroup(jPanelArrowLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 115, Short.MAX_VALUE));
        jPanelArrowLayout.setVerticalGroup(jPanelArrowLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 114, Short.MAX_VALUE));

        jTextFieldTracks.setEditable(false);
        jTextFieldTracks.setBackground(new Color(255, 255, 255));
        jTextFieldTracks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTracksActionPerformed(evt);
            }
        });

        jTextFieldX.setEditable(false);
        jTextFieldX.setBackground(new Color(255, 255, 255));
        jTextFieldX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldXActionPerformed(evt);
            }
        });

        jTextFieldFaults.setEditable(false);
        jTextFieldFaults.setBackground(new Color(255, 255, 255));
        jTextFieldFaults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFaultsActionPerformed(evt);
            }
        });

        jTextFieldFPS.setEditable(false);
        jTextFieldFPS.setBackground(new Color(255, 255, 255));
        jTextFieldFPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFPSActionPerformed(evt);
            }
        });

        jLabel8.setText("Z");

        jTextFieldZ.setEditable(false);
        jTextFieldZ.setBackground(new Color(255, 255, 255));
        jTextFieldZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZActionPerformed(evt);
            }
        });

        jTextFieldInliers.setEditable(false);
        jTextFieldInliers.setBackground(new Color(255, 255, 255));
        jTextFieldInliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInliersActionPerformed(evt);
            }
        });

        Speed.setText("Speed");

        jTextFieldSpeed.setEditable(false);
        jTextFieldSpeed.setBackground(new Color(255, 255, 255));
        jTextFieldSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSpeedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                        .createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                                .createSequentialGroup().addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout
                                                .createSequentialGroup().addComponent(Delay)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxDelay, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53,
                                                        53))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)))
                                .addGap(0, 14, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup().addGroup(layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanelArrow, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Tracks).addComponent(Inliers).addComponent(Faults)
                                                .addComponent(jLabel7).addComponent(jLabel6)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jLabel8,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(FPS, javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldTracks,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup().addGap(1, 1, 1)
                                                                .addComponent(jTextFieldInliers,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jTextFieldFaults,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup().addGap(1, 1, 1)
                                                                .addComponent(jTextFieldY,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup().addGap(1, 1, 1)
                                                                .addComponent(jTextFieldX,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup().addGap(1, 1, 1)
                                                                .addComponent(jTextFieldFPS,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 58,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup().addGap(1, 1, 1)
                                                                .addGroup(layout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTextFieldSpeed,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                58,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTextFieldZ,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                58,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(Speed, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPaneL, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanelR,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addGap(25, 25, 25).addGroup(layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBoxDelay, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Delay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tracks)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldTracks, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldInliers,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Inliers))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldFaults,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Faults))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldFPS,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(FPS))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldX,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldY,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7))
                                                .addGap(5, 5, 5)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextFieldZ,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Speed))
                                .addGap(58, 58, 58)
                                .addComponent(jPanelArrow, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanelR, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPaneL, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void jComboBoxDelayActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxDelayActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jComboBoxDelayActionPerformed

    public void jTextFieldTracksActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTracksActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldTracksActionPerformed

    public void jTextFieldFaultsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFaultsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldFaultsActionPerformed

    public void jTextFieldFPSActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldFPSActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldFPSActionPerformed

    public void jTextFieldXActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldXActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldXActionPerformed

    public void jTextFieldYActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldYActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldYActionPerformed

    public void jTextFieldZActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldZActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldZActionPerformed

    public void jTextFieldInliersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldInliersActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldInliersActionPerformed

    public void jTextFieldSpeedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldSpeedActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldSpeedActionPerformed

    public void uploadImage(BufferedImage image) {
        Graphics g = jPaneL.getGraphics();
        g.drawImage(image, 0, 0, image.getWidth(), image.getHeight(), null);
        g.dispose();
    }

    public void uploadArrowImage(BufferedImage image, int angle) {
        Graphics g = jPanelArrow.getGraphics();
        // The required drawing location
        int drawLocationX = 0;
        int drawLocationY = 0;

        // Rotation information

        double rotationRequired = Math.toRadians(-angle + 45);
        double locationX = image.getWidth() / 2;
        double locationY = image.getHeight() / 2;
        AffineTransform tx = AffineTransform.getRotateInstance(rotationRequired, locationX, locationY);
        AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);

        // Drawing the rotated image at the required drawing locations
        g.drawImage(op.filter(image, null), drawLocationX, drawLocationY, null);
        // g.drawImage(image, 0, 0, image.getWidth(), image.getHeight(), null);
        g.dispose();
    }

    int prvX = 0, prvY = 0;

    public void drawPoint(int x, int y) {
        Graphics2D g = (Graphics2D) jPanelR.getGraphics();
        g.fillOval(x, y, 4, 4);
        // g.draw3DRect(x, y, 40, 40, true);
        // g.drawLine(prvX, prvY, x, y);
        prvX = x;
        prvY = y;
        g.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Delay;
    public javax.swing.JLabel FPS;
    public javax.swing.JLabel Faults;
    public javax.swing.JLabel Inliers;
    public javax.swing.JLabel Speed;
    public javax.swing.JLabel Tracks;
    public javax.swing.JComboBox jComboBoxDelay;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPaneL;
    public javax.swing.JPanel jPanelArrow;
    public javax.swing.JPanel jPanelR;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextFieldFPS;
    public javax.swing.JTextField jTextFieldFaults;
    public javax.swing.JTextField jTextFieldTracks;
    public javax.swing.JTextField jTextFieldInliers;
    public javax.swing.JTextField jTextFieldSpeed;
    public javax.swing.JTextField jTextFieldX;
    public javax.swing.JTextField jTextFieldY;
    public javax.swing.JTextField jTextFieldZ;
    // End of variables declaration//GEN-END:variables
}
